#----------------------------------------------------------------
# No obvious benefit of group size in wild Damaraland mole-rats Fukomys damarensis
#
# iii- "Body condition of single females" 
#
# R script
# Authors: Jack Thorley, Hanna Bensch, Markus Zottl
# Contact: jackthorley1@gmail.com
#----------------------------------------------------------------


library(smatr) ; library(lme4) ; library(tidyverse)

# In this script we explore the body condition of single females in comparison to within-group non-breeders. 
teethwidth <- read.csv("FieldMR_SingleFemaleCondition_TeethWidth.csv", header = TRUE) # Females(first captured < 80g)
bodylength <- read.csv("FieldMR_SingleFemaleCondition_BodyLength.csv", header = TRUE) # Females(first captured < 80g)


# Following Peig and Green 2009
#--------------------------------

# Step 1) Plot allometric relationship on a ln scale

# body length ~ incisor width
plot(log(weight) ~ log(TeethWidth), data = teethwidth, las = 1, ylab = "ln Mass, g", xlab = "ln Incisor Width, mm", col = adjustcolor("grey30", alpha.f = 0.6))
points(log(weight) ~ log(TeethWidth), data = subset(teethwidth, statecode == "single"), col = adjustcolor("darkorange", alpha.f = 0.5), pch = 16)

# body mass ~ body length
plot(log(weight) ~ log(BodyLength), data = bodylength, las = 1, ylab = "ln Mass, g", xlab = "ln Body Length, cm", col = adjustcolor("grey30", alpha.f = 0.6))
points(log(weight) ~ log(BodyLength), data = subset(bodylength, statecode == "single"), col = adjustcolor("darkorange", alpha.f = 0.5), pch = 16)

# Step 2) Perform a standard major axis regression on logged weights using the smatr package

teethwidth$weight.ln <- log(teethwidth$weight)
bodylength$weight.ln <- log(bodylength$weight)

teethwidth$teethwidth.ln <- log(teethwidth$TeethWidth)
bodylength$bodylength.ln <- log(bodylength$BodyLength)

sma <- sma(weight.ln ~ teethwidth.ln, data = teethwidth) # slope = 2.565642
#sma.rob <- sma(weight.ln ~ teethwidth.ln, data = teethwidth, robust = T) # 2.662088

sma2 <- sma(weight.ln ~ bodylength.ln, data = bodylength) # slope = 3.336605
#sma.rob2 <- sma(weight.ln ~ bodylength.ln, data = bodylength, robust = T) # slope = 3.349365

summary(sma)
#summary(sma.rob) 

summary(sma2)
#summary(sma.rob2) 

# calculate the scaled mass index relative to the population mean for each trait
x.0 <- mean(teethwidth$teethwidth)  # 1.75
teethwidth$massindex <- teethwidth$weight * (x.0 / teethwidth$teethwidth) ^ 2.565642

x.1 <- mean(bodylength$BodyLength)   # 17.53
bodylength$massindex <- bodylength$weight * (x.1 / bodylength$BodyLength) ^ 3.336605

# note that in the above I have assumed that males and females have the same scaling relationship
sma.bystatecode <- sma(teethwidth.ln ~ weight.ln + statecode, data = teethwidth)
summary(sma.bystatecode) # the output suggests that this is completely valid- no sex difference in scaling

sma2.bystatecode <- sma(bodylength.ln ~ weight.ln + statecode, data = bodylength)
summary(sma2.bystatecode) # the output suggests that this is completely valid- no sex difference in scaling

# replot the sma with confidence intervals generated by bootstrapping
# create new data set at a high resolution (200 points from min to max)
preds <- data.frame(expand.grid(teethwidth.ln = seq(min(teethwidth$teethwidth.ln), max(teethwidth$teethwidth.ln), length.out = 200)))

# bootstrap data and get predictions
preds <- teethwidth %>%
  # create new bootstrapped data sets
  modelr::bootstrap(n = 1000, id = 'boot_num') %>%
  # fit sma to every bootstrap
  group_by(boot_num) %>%
  mutate(., fit = map(strap, ~ sma(weight.ln ~ teethwidth.ln, data=data.frame(.), method="SMA"))) %>%
  ungroup() %>%
  # extract intercept and slope from each fit
  mutate(., intercept = map_dbl(fit, ~coef(.x)[1]),
         slope = map_dbl(fit, ~coef(.x)[2])) %>%
  dplyr::select(., -fit) %>%
  # get fitted values for each bootstrapped model
  # uses the preds dataframe we made earlier
  group_by(boot_num) %>%
  do(data.frame(fitted = .$intercept + .$slope*preds$teethwidth.ln, 
                teethwidth.ln = preds$teethwidth.ln)) %>%
  ungroup() 


preds <- preds %>%
  # calculate the 2.5% and 97.5% quantiles at each teeth width value
  group_by(., teethwidth.ln) %>%
  dplyr::summarise(., conf_low = quantile(fitted, 0.025),
                   conf_high = quantile(fitted, 0.975)) %>%
  ungroup()  %>% 
  data.frame()

# plot the results of the best fitting SMA regression for body mass on teethwidth
plot(log(weight) ~ log(TeethWidth), data = teethwidth, las = 1, ylab = "ln Mass, g", xlab = "ln Incisor Width, mm", col = adjustcolor("grey30", alpha.f = 0.6), ylim = c(4.3, 5.3))
points(log(weight) ~ log(TeethWidth), data = filter(teethwidth, statecode == "single"), col = adjustcolor("darkorange", alpha.f = 0.5), pch = 16)
polygon(c(preds$teethwidth.ln, rev(preds$teethwidth.ln)), 
        c(preds$conf_low, rev(preds$conf_high)),
        col= adjustcolor("red", alpha.f = 0.2),border=NA)
abline(a = 0.24130990, b = 2.565642, col = "black", lwd = 2) # summary(sma)

# Model this in lmer to control for repeat measures on individuals.
conditionmod <- lme4::lmer(massindex ~ statecode + (1|AnimalID),
                           data = teethwidth)
summary(conditionmod)

# plot the results of the best fitting SMA regression for body mass on body length
preds2 <- data.frame(expand.grid(bodylength.ln = seq(min(bodylength$bodylength.ln), max(bodylength$bodylength.ln), length.out = 200)))

# bootstrap data and get predictions
preds2 <- bodylength %>%
  # create new bootstrapped data sets
  modelr::bootstrap(n = 1000, id = 'boot_num') %>%
  # fit sma to every bootstrap
  group_by(boot_num) %>%
  mutate(., fit = map(strap, ~ sma(weight.ln ~ bodylength.ln, data=data.frame(.), method="SMA"))) %>%
  ungroup() %>%
  # extract intercept and slope from each fit
  mutate(., intercept = map_dbl(fit, ~coef(.x)[1]),
         slope = map_dbl(fit, ~coef(.x)[2])) %>%
  dplyr::select(., -fit) %>%
  # get fitted values for each bootstrapped model
  # uses the preds dataframe we made earlier
  group_by(boot_num) %>%
  do(data.frame(fitted = .$intercept + .$slope*preds2$bodylength.ln, 
                bodylength.ln = preds2$bodylength.ln)) %>%
  ungroup() 

preds2 <- preds2 %>%
  # calculate the 2.5% and 97.5% quantiles at each teeth width value
  group_by(., bodylength.ln) %>%
  dplyr::summarise(., conf_low = quantile(fitted, 0.025),
                   conf_high = quantile(fitted, 0.975)) %>%
  ungroup()  %>% 
  data.frame()

# plot the results of the best fitting SMA regression for body mass on teethwidth
plot(log(weight) ~ log(BodyLength), data = bodylength, las = 1, ylab = "ln Mass, g", xlab = "ln Body Length, cm", col = adjustcolor("grey30", alpha.f = 0.6))
points(log(weight) ~ log(BodyLength), data = filter(bodylength, statecode == "single"), col = adjustcolor("darkorange", alpha.f = 0.5), pch = 16)
polygon(c(preds2$bodylength.ln, rev(preds2$bodylength.ln)), 
        c(preds2$conf_low, rev(preds2$conf_high)), 
        col= adjustcolor("red", alpha.f = 0.2),border=NA)
abline(a = -4.833573 , b = 3.336605, col = "black", lwd = 2) # summary(sma2)

# Model this in lmer to control for repeat measures on individuals.
conditionmod2 <- lmer(massindex ~ statecode + (1|AnimalID),
                           data = bodylength)
summary(conditionmod2)


#####-----------------  END   ------------------####
